spring:
  config:
    import: optional:file:.env.${EXEC_PROFILE}.properties
  application:
    name: jordel
  security:
    user:
      name: user
      password: root
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: ${DB_DIALECT}
  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml
    contexts: ${EXEC_PROFILE}
    parameters:
      autoIncrement: true
  messages:
    basename: "lang/messages,lang/error"
    encoding: UTF-8
    fallback-to-system-locale: false
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${SMTP_USER}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp-relay.brevo.com
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

logging:
  level:
    org:
      springframework:
        security: TRACE

server:
  port: 7001

jwt:
  secret: "96eee8811a493fac99a85c1fa12095ba56ca533aebafd2f194aeb96ff5b1b1f775893edcf9671d8565d4c8d37d6dc8fd203dd05867778cfcb22b21c35c56e1f4f7939b7c7d886a8df9780665095d1052d4c7f1dd68332073ca61a08f5b69305c3acdf44229f408eac3798b3892683093617df9fdc1220db03f406c87b4c107215e37eba0a6db92faa4defb632f570c02c0001c519391acf1a73062a21ee7d3cd0d7e7b218b1df1c74253dcc265dc6640fc7bf948a3c84b38d4fc9c40398846264c75c4d315d20d6845872e1518c3e8f19b16fb592b2d14d152ad0831d2e5be8b0b7393255dcc44c45b047ff491ca91cbd4d5b1dc9f919904cd9bffe4f1b0d0aa"
  expiration:
    access: 900000
    refresh: 2592000000

cors:
  allowed_hosts: ${ALLOWED_HOSTS}

brevo:
  api:
    key: k4dHO9JpsatADPMx
  sender:
    email: "bloodbowlclub@gmail.com"
    name: "BloodBowl Club"

email:
  default:
    sender:
      name: "BloodBowl Club"
      email: "bloodbowlclub@gmail.com"